---
  
- name: Configure interface toward ACI
  template: src=01-netcfg.yaml.j2 dest=/etc/netplan/01-netcfg.yaml

- name: Configure dhcp for ACI
  template: src=dhclient.conf.j2 dest="/etc/dhcp/dhclient.conf"

- name: Netplan Apply
  command: sudo netplan apply

- name: Disable swap
  command: swapoff -a

- name: Remove swap entry from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Test http internet connectivity get http://www.google.com
  uri:
    url: http://www.google.com
    
- name: Test https internet connectivity get https://www.google.com
  uri:
    url: https://www.google.com
  
- name: add apt-key for Kubeadm
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubernetes repo
  copy:
    content: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    dest: /etc/apt/sources.list.d/kubernetes.list
    force: no

- name: Update repos
  apt:
    update_cache: yes
    upgrade: no
   
- name: install docker
  apt:
    name: docker.io
    state: latest
- name: Install kubeadm, kubelet and kubectl 
  apt: 
    name: kubelet={{ kube_version }},kubectl={{ kube_version }},kubeadm={{ kube_version }}
    state: present

