---
- name: Reset cluster
  command: kubeadm reset -f

- name: Join to Kubernetes cluster
  command: kubeadm join  --token {{ kubeadm_token }}  {{ hostvars[groups['kube-master'][0]]['ip'] }}:6443 --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors='all'

- name: Enable and restart kubelet 
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  
